### ISSUE TITLE
Invisible commands

### ISSUE THREAD

**Issue by temp** [puli/puli#24]
I just played with the type command, and asked myself how I can define types via the cli.
While looking into the command classes I found TypeDefineCommand and TypeRemoveCommand, but both are not shown in the help summary of puli. Don't know wether or not this is a symfony/console bug, since both commands "type define" and "type remove" have spaces in their names.
Maybe just rename them to "type-define" and "type-remove"?

**Comment by webmozart** [comment]
They are shown when you do `puli help -a` and will be shown when doing `puli type -h` - this is still WIP.

The space in the name is on purpose and an extension of the Symfony Console. I wanted to achieve a Git-like user experience:

```php
$ puli type
$ puli type define my/type
$ puli type remove my/type
```

Cheers!

**Comment by temp** [comment]
Ah, didn't see the CompositeCommand in the TypeDefineCommand.
And I wondered about the <sub-command> hint in the help. But didn't think about it ;-)
