### ISSUE TITLE
More versatile ls command

### ISSUE THREAD

**Issue by temp** [puli/puli#27]
It would be nice if the ls command would not only accept <directory> as a parameter, but also query strings and types.
Query strings: bin/puli ls /whatever/*/*.js
Types: bin/puli ls my/type

**Comment by webmozart** [comment]
I am planning to add a `puli find` command that will do that. Also, I am planning to make `puli ls` more similar to the UNIX `ls` command:

Rough sketch:

```
$ puli ls
app  acme  puli
$ puli ls -l
DirectoryResource 4,0K Jan  6 09:02 app
DirectoryResource 4,0K Jan  6 08:45 acme
DirectoryResource 4,0K Jan  3 10:02 puli
$ puli ls -l /app
DirectoryResource 4,0K Jan  6 09:02 config
DirectoryResource 4,0K Jan  6 08:45 css
DirectoryResource 4,0K Jan  3 10:02 views
$ puli find *.twig
/app/views/index.html.twig
/app/views/layout.html.twig
```

What do you think?

**Comment by webmozart** [comment]
As for types:

```
$ puli find -type puli/web-resource
/app/css/reset.css
/app/css/style.css
```

**Comment by temp** [comment]
Yeah, -l would have been my next suggestion ;-)

I'm a bit undetermined about a seperate find command with a pattern - as a linux user I would think that ls does that. From your developer sight I understand that you split it into ls and find, since puli works internally like that. But from a usability sight I would vote for a unified ls command.

puli ls /test
puli find /test/*.js
puli ls /test/whatever.js
That seems unnecessary.

puli ls /test
puli ls /test/*.js
puli ls /test/whatever.js
This is what I would expect.

For types... dunno. 
puli ls -type my/type
Guess this would work here, too.

**Comment by webmozart** [comment]
> as a linux user I would think that ls does that

Really? I wouldn't - for me those commands have very different purposes (both on Linux and in Puli):

* ls lists the contents of a directory. As a result, you get the names of the entries of one directory only.
* find lists files according to a search criteria. As a result, you get the absolute paths of all matches.

We can only unify the two commands if we let `puli ls` return absolute paths, which does not make sense for listing a directory - because I already know where I am.

**Comment by temp** [comment]
Agreed. Again, I didn't think enough about it, since listing files with patterns is more like unix find than unix ls.
+1 for find!

**Comment by webmozart** [comment]
Thanks for your feedback! :) I appreciate it a lot.

**Comment by temp** [comment]
![BETA TEST ALL THE THINGS!](http://cdn.meme.am/instances/500x/57797004.jpg)
