### ISSUE TITLE
[twig-extension] Error on empty template

### ISSUE THREAD

**Issue by temp** [puli/puli#28]
We just switched to loading twig templates via puli, and got an error on an empty twig template.
Since the template was empty before, and it didn't throw an error, I think puli might have a problem with it.
When I put a test string inside the template file, it works again.

Exceptions are only thrown by twig:

```
[2/2] Twig_Error_Syntax: An exception has been thrown during the compilation of a template ("Node "0" does not exist for Node "Twig_Node_Body".") in "/form/views/FormElements/backendfield.html.twig".   +
[1/2] LogicException: Node "0" does not exist for Node "Twig_Node_Body".   +
```

Code fragment to reproduce:
```
    /**
     * @Route("/test1", name="test1")
     *
     * @return RedirectResponse
     */
    public function test1Action()
    {
        // error from above
        return $this->render('/test/test.html.twig');
    }

    /**
     * @Route("/test2", name="test2")
     *
     * @return RedirectResponse
     */
    public function test2Action()
    {
        // works, empty page
        return $this->render('@Test/test.html.twig');
    }

```

**Comment by temp** [comment]
Both statements point to the same template, of course.
First via puli, second via symfony file locator.

**Comment by temp** [comment]
Is this a bigger problem?

**Comment by webmozart** [comment]
No, I just haven't found the time yet. Fixed now. :)

**Comment by temp** [comment]
Excellent! Works, thanks!
