### ISSUE TITLE
[Doc] Outdated description of Puli components

### ISSUE THREAD

**Issue by stof** [puli/puli#29]
The description of puli components in http://docs.puli.io/en/latest/components.html is incomplete. It misses the discovery system

**Comment by webmozart** [comment]
Thanks for reporting. Yes, the docs are momentarily out of date, there have been a lot of changes which are not reflected yet. See also #25.

**Comment by webmozart** [comment]
I updated the page now:
http://docs.puli.io/en/latest/components.html
