### ISSUE TITLE
Development workflow

### ISSUE THREAD

**Issue by temp** [puli/puli#30]
We have been evaluating puli now for a few days, everything works fine. But we are having problems with the development workflow.
Right now we are using puli for templates and form configuration xml files.
But everytime we change one of these files, we have to call puli build, which is a really nuisance.
Is there anything we can do to automate this? How are you developing content with puli?
Maybe there should be a development mode which automatically rebuilds the repository on changes?
Or a puli build --watch command?

**Comment by webmozart** [comment]
Thanks for your feedback! The solution to this problem depends on the platform you use.

For Linux, there is only one small crucial feature missing, and that's the use of symlinks in FilesystemRepository. Then you only have to rebuild the repository after installing packages (and there it's done automatically).

On Windows, we don't have symlinks. For that I thought of two solutions:

* the `--watch` option as you suggested
* a different repository implementation than FilesystemRepository, which stores the serialized resources or the filesystem paths in a key-value store

Which platform do you develop on?

**Comment by temp** [comment]
The team mainly uses mac os x, so symlinks are welcome.
But there is one diehard windows user, which resists to switch to a more develop-friendly os... ;-)
So, too bad, a mixed environment.

**Comment by webmozart** [comment]
I see. I'll soon implement the symlinks, they're fairly simple. Watching is a bit more tricky, but feel free to submit a PR for that. :)

**Comment by temp** [comment]
We would stick to a grunt watch task, but it does not work on windows. :-(
As for a PR, I'd live to do that, but our project has an evil deadline. Will see when/how I will be able to contribute.

Nevertheless - love puli, good job!

**Comment by webmozart** [comment]
I just read that apparentely Windows > Vista supports symbolic links!
http://de.php.net/symlink

**Comment by temp** [comment]
Yes, Windows support symlinks in newer versions, but I remember there are problems with windows+php+symlinks.

Oh, nevermind, from http://php.net/manual/en/function.symlink.php:
Note: Windows users should note that this function will only work if the system you run PHP from is Windows Vista/Windows Server 2008 or newer. Windows versions prior to that does not support symbolic links.

Awesome!

**Comment by webmozart** [comment]
This is implemented now, just run `puli build -f`. Symlinks are used by default, if possible. On Windows < Vista or Server 2008, files will always be copied.

You can manually disable symlinks in the configuration:

```json
{
    "config": {
        "repository": {
            "symlink": false
        }
    }
}
```

Delete .puli/PuliFactory.php (this is going to happen automatically soon) and run `puli build -f`.

**Comment by temp** [comment]
First response from the windows user - works with admin rights, but not without.
Seems to be forbidden by a domain policy with the default settings.
But that's a problem on our side ;-)
Will try it out here, too.

**Comment by webmozart** [comment]
Ok, I read about that. In the final version of Puli there will hopefully be the possibility of using a local config file that overrides puli.json, which your Windows user could use in this case to turn off symlinks. That of course doesn't solve your problem. The only solution in that case is to use an alternative repository implementation (maybe on Windows only).

**Comment by temp** [comment]
It's not really that big a problem right now. After the symlinks have been created the error will only arise for new files. And then he has to run a manual puli build with admin privileges.

**Comment by webmozart** [comment]
Ok, sounds good. :)

**Comment by temp** [comment]
Looking good! No problems found.

**Comment by webmozart** [comment]
Great :) Thanks for the feedback!

**Comment by stof** [comment]
@webmozart note that even on newer versions of Windows, the ability to create symlinks from PHP depends on the permissions of the user running PHP (using admin privileges grants such permission, but is is also possible to grant the finer-grained permission to the user itself). This is why Symfony's ``asset:install`` command has been refactored in 2.6 to be able to try using symlinks and then using a hard copy as fallback when it is not possible (allowing to use symlinks as often as possible)

**Comment by webmozart** [comment]
Thanks @stof! I created a ticket for this issue.

**Comment by webmozart** [comment]
This should be fixed by puli/repository@e6d2cf01b0d17b95891a294a23ba0ec24303fb47. Can you verify?

**Comment by temp** [comment]
I got a reply-mail for this ticket from you, webmozart, but I can't find the comment?
"This should be fixed by puli/repository@e6d2cf0. Can you verify?"
Have you deleted this comment?

**Comment by webmozart** [comment]
Yes, I deleted the comment as I replied to the wrong ticket. :)

Anyway, symlinks on Windows *should* be fixed now.

**Comment by temp** [comment]
Ah ok, this was confusing, thanks for the clarification!
