### ISSUE TITLE
Removal of a composer dependency

### ISSUE THREAD

**Issue by temp** [puli/puli#32]
I just removed a dependency from composer.json and ran composer update, resulting in this error:

```
Generating PULI_FACTORY_CLASS constant
Registering Puli\GeneratedPuliFactory with the class-map autoloader

  [Puli\RepositoryManager\FileNotFoundException]
  Could not load package: The directory /Users/swentz/Sites/phlexible-tipfinder/tipfinder/vendor/mikey179/vfsStream does not exist.
```

Doesn't puli recognize the removal of a package, yet?
After removing mikey179/vfsStream from puli.json/packages

**Comment by webmozart** [comment]
Thanks for reporting! Removal of packages is broken ATM. I'm going to fix this the next days.

**Comment by webmozart** [comment]
This is fixed now.
